---
title: "GDAT626 - Final Project"
author: "John Viviani"
date: "11/30/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

c("dplyr",
  "forecast",
  "tseries",
  "data.table", 
  "ggplot2",
  "tensorflow",
  "tidyr",
  "rio"
  ) -> package_names  
for(package_name in package_names) {
  if(!is.element(package_name, installed.packages()[,1])) {
     install.packages(package_name,
                      repos = "http://cran.mtu.edu/")
  }
  library(package_name, character.only=TRUE,
          quietly=TRUE,verbose=FALSE)
}

rm(list=c("package_name", "package_names")) # clean up the environment
```

## EXPLORATORY DATA ANALYSIS
```{r Exploratory Data Analysis}
# Reading in the Data
read.csv("C:/Users/John.JVivs/Documents/COLLEGE/GRAD SCHOOL/GDAT626/PROJECT/MCD.csv") -> mcd

# Check for NAs
anyNA(mcd)
# No NAs

# Historical data from 2014-2019 on McDonald's stock prices
str(mcd)

# Convert into proper date format
mcd$Date <- as.Date(mcd$Date)

# Visualize the Data
ggplot(mcd, aes(Date, Close)) + 
  geom_line() + 
  ylab("Closing Stock Value") + 
  xlab("Time") + 
  ggtitle("Daily Closing Values of McDonald's Stock")
# Maybe a positive, linear trend? Can't tell for sure if it's stationary.

# Stock prices are based on returns, and returns based on percentages. Important to normalize these values.

# Building a normalize() function
normalize <- function(x) {
  num <- x - min(x)
  denom <- max(x) - min(x)
  return (num/denom)
}

mcd_norm <- as.data.frame(lapply(mcd[5], normalize))
# Now we have normalized values (between 0 and 1) on the Close values (Going to focus on the closing values for this predictive model)

# Attaching date column to normalized data set
mcd$Date -> mcd_norm$Date

# Weekly moving averages
mcd_norm$cnt_ma = ma(mcd_norm$Close, order=7)

# Plotting the daily stock values versus the weekly moving average
ggplot() + 
  geom_line(data = mcd_norm, aes(x = Date, y = Close, colour = "Counts")) + 
  geom_line(data = mcd_norm, aes(x = Date, y = cnt_ma, colour = "Weekly Moving Average")) + 
  ylab("Closing Stock Value")
# Weekly moving average looks smoother. Be careful not to oversmooth; negatively impacts accuracy.
# Regardless, weekly still looks good to move on with.
```

## DECOMPOSING THE DATA
```{r DECOMPOSING THE DATA}
# Building a weekly moving average
count_ma = ts(na.omit(mcd_norm$cnt_ma), frequency = 252) # Frequency based on number of days the stock market is open
decomp = stl(count_ma, s.window = "periodic")
deseasonal_cnt <- seasadj(decomp) # Removes the seasonality; used later in ARIMA model
plot(decomp)
# Check out the first graph; smoothed out since we're looking at the weekly moving average.
# Still not sold on it being stationary; let's test it.

# Let's look at the acf/pacf
acf(count_ma)
pacf(count_ma)
# Acf plot is looking rough... Let's apply diff to it, then try again.

# Differencing
diff(deseasonal_cnt, differences = 1) -> count_d1
plot(count_d1)

# acf/pacf of the differenced values
acf(count_d1, lag.max = 20)
pacf(count_d1, lag.max = 20)

# Let's use the Dickey-Fuller test to screen for stationarity across the original, differenced, and weekly moving average time-series

# Original ts
adf.test(mcd_norm$Close)
# This confirms my assumption that it wasn't stationary earlier. High p-value of 0.4011 cannot reject the null hypothesis of non-stationarity.

# Differenced ts
diff(mcd_norm$Close) -> diff_mcd
adf.test(diff_mcd)
# The differenced ts yields a p-value of 0.01, which allows us to reject the null hypothesis of non-stationarity.
# Therefore, the differenced ts is stationary. May be valuable to try an auto.arima.
plot(ts(diff_mcd))

# Weekly moving average
adf.test(count_ma)
# p-value of 0.3309; cannot reject the null; therefore, non-stationary (as expected from ugly looking acf plot)

# Differenced weekly moving average
adf.test(count_d1)
# Differenced ts of the weekly moving average yields a p-value of 0.01, which can reject the null hypothesis of non-stationarity.
# Therefore, the differenced ts of the weekly moving average is stationary.
```

## BUILDING AN ARIMA MODEL
```{r BUILDING AN ARIMA MODEL}
# Let's see what auto.arima suggests for the model
auto.arima(deseasonal_cnt, seasonal = FALSE) # Note: Using the non-seasonal data (don't want seasonality)
# Suggests (4,1,5)

# Taking a look at the auto arima
fit <- auto.arima(deseasonal_cnt, seasonal = FALSE)
tsdisplay(residuals(fit), lag.max = 45, main = '(1,1,1) Model Residuals')
# Not sold on entirely trusting the auto arima

# ARIMA of deseasonal_cnt 4,1,5 (Suggested by auto.arima at one point)
fit3 <- arima(ts(deseasonal_cnt[522:772]), order=c(4,1,5))
forecast_fit3 <- forecast(fit3, h=30)
tsdisplay(residuals(fit3), lag.max = 45, main='Non-Seasonal Model Residuals (4,1,5)')

# Manually fitting with arima to find model with acceptable lags from acf/pacf plots
## 2nd order, 1 diff, lag at 8.
fit2 <- arima(deseasonal_cnt, order=c(2,1,8))
tsdisplay(residuals(fit2), lag.max = 45, main = 'Seasonal Model Residuals')
# This generates acf/pacf plots that look much better. All lags fall within the blue lines. Let's roll with this model.

# Subset
# 30 stock days that we want to predict
pred <- ts(deseasonal_cnt[773:802])
# Subset from 1/3/2017 to 12/29/2017. Using ARIMA that we manually made earlier.
fit_subset <- arima(ts(deseasonal_cnt[522:772]), order=c(2,1,8))
# Forecasting the subset to predict the next 30 stock days
forecast_subset <- forecast(fit_subset, h=30)
plot(forecast_subset)
lines(ts(deseasonal_cnt[522:802])) # Plotting it against the actual values that were withheld (the next 30 stock days).
# The predictive model fails. It assumes a positive, linear trend, whereas the actual model only increases briefly before plummeting.
```

## ADDITIONAL ANALYSIS
```{r ADDITIONAL ANALYSIS}
# Auto ARIMA of non-seasonal data
tsdisplay(residuals(fit), lag.max = 20, main='Non-Seasonal Model Residuals Auto ARIMA')

# Auto ARIMA of deseasonal_cnt 4,1,5
tsdisplay(residuals(fit3), lag.max = 20, main='Non-Seasonal Model Residuals (4,1,5)')

# ARIMA deseasonal_cnt 2,1,8 (model we decided would be best)
tsdisplay(residuals(fit2), lag.max = 20, main='Non-Seasonal Model Residuals (2,1,8)')

# Compare each of the models
par(mfrow=c(3,1))

# Auto ARIMA of non-seasonal data
fit1 <- auto.arima(ts(deseasonal_cnt[522:772]))
forecast_fit1 <- forecast(fit1, h=30)
plot(forecast_fit1)

# ARIMA of deseasonal_cnt 4,1,5 (Suggested by auto.arima at one point)
plot(forecast_fit3)

# ARIMA deseasonal_cnt 2,1,8 (model we decided would be best)
plot(forecast_subset)

# Adding seasonality back in to auto ARIMA
fit1_seasonal <- auto.arima(ts(deseasonal_cnt[522:772]), seasonal = TRUE)
forecast_fit1_seasonal <- forecast(fit1_seasonal, h=30)
plot(forecast_fit1_seasonal)
tsdisplay(residuals(fit1_seasonal), lag.max = 20, main = 'Seasonal Auto ARIMA Model')
# Still bad performs poorly.

```

